#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd net.frontuari.customcreatefrom.targetplatform
./plugin-builder $DEBUG_MODE ../net.frontuari.customcreatefrom ../net.frontuari.customcreatefrom.test
